---

- name: Delete node from cluster
  shell: kubectl delete node "{{ node_name }}"
  delegate_to: "{{ groups.cloud_masters | first }}"
  when: not is_first_master_node
  ignore_errors: true

- name: Destroy cluster
  shell: kubeadm reset --force

