---

- name: Generate cluster config
  template:
    src: ../templates/cluster_configuration.yaml.j2
    dest: /etc/kubernetes/cluster_configuration.yaml

- name: Initialize cluster
  shell: kubeadm init --skip-token-print --node-name {{ node_name.stdout }} --config /etc/kubernetes/cluster_configuration.yaml

