---

- name: Generate haproxy config
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Generate keepalived config
  template:
    src: ../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start haproxy
  shell: systemctl start haproxy
  ignore_errors: true

- name: Start keepalived
  shell: systemctl start keepalived
