---

- name: Generate cluster join command
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups.cloud_masters | first }}"
  register: cluster_join_token

- name: Generate cluster certificate key
  shell: kubeadm init phase upload-certs --upload-certs | grep -v "\["
  register: cluster_certificate_key
  delegate_to: "{{ groups.cloud_masters | first }}"

- name: Join Kubernetes cluster
  shell: "{{ cluster_join_token.stdout }} --control-plane --certificate-key {{ cluster_certificate_key.stdout }} --node-name {{ node_name.stdout }}"

