---

- name: Get node name
  shell: hostname 
  register: node_name

- name: Check if cluster exists
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: cluster_exists

- name: Destroy cluster
  include_tasks: destroy_cluster.yml
  when: cluster_exists.stat.exists

- name: Initialize cluster
  include_tasks: initialize_cluster.yml
  when: is_first_master_node

- name: Add user
  include_tasks: add_user.yml
  when: is_first_master_node

- name: Install network
  include_tasks: install_network.yml
  when: is_first_master_node

- name: Join workers
  include_tasks: join_worker.yml
  when: not is_master_node
