---

- name: Make .kube directory
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory

- name: Copy config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
  run_once: true

- name: Grant permissions to config
  file:
    path: $HOME/.kube/config
    owner: "{{ k8s_admin_user }}"
    mode: 0600
  run_once: true

- name: Copy config to local user
  fetch:
    src: /home/{{ k8s_admin_user }}/.kube/config
    dest: /home/{{ k8s_admin_user }}/.kube/config
    flat: true
  run_once: true

- name: Copy config to machines
  copy:
    src: /home/{{ k8s_admin_user }}/.kube/config
    dest: /home/{{ k8s_admin_user }}/.kube/config

- name: Change entrypoint for local
  lineinfile:
    path: $HOME/.kube/config
    regexp: "server:"
    line: "    server: https://localhost:{{ k8s_api_port }}"
  delegate_to: localhost
  run_once: true
